/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define COMBO_ONLY_FROM_LAYER 0
#define TAPPING_TERM_PER_KEY
#define COMBO_TERM_PER_COMBO
#define AUTO_SHIFT_MODIFIERS
#define AUTO_SHIFT_TIMEOUT 150
#define TAPPING_TOGGLE 2
#define COMBO_SHOULD_TRIGGER
#define PERMISSIVE_HOLD_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
